export const languages = [
    { value: 'English', label: 'English' },
    { value: 'Assamese', label: 'Assamese' },
    { value: 'Bengali', label: 'Bengali' },
    { value: 'Bodo', label: 'Bodo' },
    { value: 'Dogri', label: 'Dogri' },
    { value: 'Gujarati', label: 'Gujarati' },
    { value: 'Hindi', label: 'Hindi' },
    { value: 'Kashmiri', label: 'Kashmiri' },
    { value: 'Kannada', label: 'Kannada' },
    { value: 'Konkani', label: 'Konkani' },
    { value: 'Maithili', label: 'Maithili' },
    { value: 'Malayalam', label: 'Malayalam' },
    { value: 'Manipuri', label: 'Manipuri' },
    { value: 'Marathi', label: 'Marathi' },
    { value: 'Nepali', label: 'Nepali' },
    { value: 'Oriya', label: 'Oriya' },
    { value: 'Punjabi', label: 'Punjabi' },
    { value: 'Sanskrit', label: 'Sanskrit' },
    { value: 'Santali', label: 'Santali' },
    { value: 'Sindhi', label: 'Sindhi' },
    { value: 'Tamil', label: 'Tamil' },
    { value: 'Telugu', label: 'Telugu' },
    { value: 'Urdu', label: 'Urdu' },
];

export const pronouns = [
    { value: 'He/him/his', label: 'He/him/his' },
    { value: 'She/her/hers', label: 'She/her/hers' },
    { value: 'They/them/theirs', label: 'They/them/theirs' },
];